class: Workflow
cwlVersion: v1.2
id: ddcal-widefield
label: Automated direction-dependent calibration for wide-field imaging
doc: |
  This is a workflow for the LOFAR-VLBI pipeline that follows on the delay-calibration and:
    * Splits a LOFAR MeasurementSet into various target directions with split-directions.cwl
    * Performs direction-dependent calibrator selection with phasediff scores (see Section 3.3 from https://arxiv.org/abs/2407.13247)
    * Performs self-calibration on the target directions with facetselfcal (with automatically tuned parameter settings)

requirements:
  - class: SubworkflowFeatureRequirement
  - class: MultipleInputFeatureRequirement

inputs:
    - id: msin
      type: Directory[]
      doc: The input MeasurementSets of the entire field-of-view with or without delay-calibration solutions applied.

    - id: source_catalogue
      type: File
      doc: External image catalogue (in CSV or FITS format) containing candidate target directions (e.g. LoTSS catalogue).

    - id: delay_solset
      type: File?
      doc: The solution tables generated by the delay calibration workflow in an HDF5 format when not applied on the msin.

    - id: dd_dutch_solutions
      type: File?
      doc: Provide already obtained direction-dependent h5parm solutions for the Dutch LOFAR array to pre-apply before international LOFAR calibration.

    - id: max_dp3_threads
      type: int?
      default: 4
      doc: Number of cores to use per job for tasks with high I/O or memory.

    - id: numbands
      type: int?
      default: -1
      doc: The number of bands to group. -1 means all bands.

    - id: truncateLastSBs
      type: boolean?
      default: true
      doc: Whether to truncate the last subbands of the MSs to the same length.

    - id: dd_selection
      type: boolean?
      default: true
      doc: If set to true the pipeline will perform direction-dependent calibrator selection.

    - id: phasediff_score
      type: float
      default: 2.3
      doc: |
         Phasediff-score to select good calibrators. See Section 3.3.1 from de Jong et al. (2024; https://arxiv.org/pdf/2407.13247)
         For calibrator selection <2.3 good for DD-calibrators and <0.7 good for DI-calibrators. If no selection set on for example value >5.
         Only used when dd_selection==true.

    - id: custom_phasediff_score_csv
      type: File?
      doc: CSV-formatted file with phasediff_scores. Overwrites the scores one generated in the DD-selection.

    - id: peak_flux_cut
      type: float
      default: 0.025
      doc: Peak flux (Jy/beam) cut to pre-select sources from catalogue.

    - id: model_cache
      type: string?
      doc: Neural network cache directory.

steps:
    - id: split_directions
      label: Split out calibrator sources in separate measurement sets
      in:
        - id: msin
          source: msin
        - id: delay_solset
          source: delay_solset
        - id: image_cat
          source: source_catalogue
        - id: max_dp3_threads
          source: max_dp3_threads
        - id: phasediff_score
          source: phasediff_score
        - id: peak_flux_cut
          source: peak_flux_cut
        - id: dd_selection
          source: dd_selection
      out:
        - msout_concat
        - phasediff_score_csv
      run: ./split-directions.cwl

    - id: ddcal_int
      label: Automatic direction-dependent calibration
      in:
        - id: msin
          source: split_directions/msout_concat
        - id: dd_dutch_solutions
          source: dd_dutch_solutions
        - id: phasediff_score_csv
          source:
            - custom_phasediff_score_csv
            - split_directions/phasediff_score_csv
          pickValue: first_non_null
        - id: model_cache
          source: model_cache
      out:
        - h5parms
        - selfcal_images
        - selfcal_inspection_images
        - solution_inspection_images
      run: ./subworkflows/ddcal_calibrators.cwl

    - id: validation
      in:
        - id: images
          source: ddcal_int/selfcal_images
        - id: h5parm
          source: ddcal_int/h5parms
        - id: model_cache
          source: model_cache
        - id: dd_selection
          source: dd_selection
      out:
        - h5parm_selected
        - images_selected
        - validate_csv
      when: $(inputs.dd_selection)
      run: ./subworkflows/ddcal_validation.cwl

    - id: multidir_merge
      in:
        - id: h5parms
          source:
            - validation/h5parm_selected
            - ddcal_int/h5parms
          pickValue: first_non_null
      out:
        - multidir_h5
      run: ../steps/multidir_merger.cwl

outputs:
    - id: final_merged_h5
      type: File
      outputSource: multidir_merge/multidir_h5
      doc: Final multi-directional h5parm

    - id: phasediff_score_csv
      type: File?
      outputSource: split_directions/phasediff_score_csv
      doc: Phasediff-score CSV file

    - id: validation_csv
      type: File?
      outputSource: validation/validate_csv
      doc: Validation CSV file

    - id: FITS_images
      type: File[]
      outputSource:
        - validation/images_selected
        - ddcal_int/selfcal_images
      pickValue: first_non_null
      doc: Best self-calibration image in FITS format

    - id: calibration_solutions
      type: File[]
      outputSource:
        - validation/h5parm_selected
        - ddcal_int/h5parms
      pickValue: first_non_null
      doc: Best self-calibration solutions in h5parm format

    - id: solution_inspection_images
      type: Directory[]
      outputSource: ddcal_int/solution_inspection_images
      doc: LoSoTo solution inspection images

    - id: selfcal_PNG_images
      type: File[]
      outputSource: ddcal_int/selfcal_inspection_images
      doc: Self-calibration images in PNG format
