class: Workflow
cwlVersion: v1.2
id: ddcal-widefield
label: Automated direction-dependent calibration for wide-field imaging
doc: |
  This is a workflow for the LOFAR-VLBI pipeline that follows on the delay-calibration and:
    * Splits a LOFAR MeasurementSet into various target directions with split-directions.cwl
    * Performs direction-dependent calibrator selection with phasediff scores (see Section 3.3 from https://arxiv.org/abs/2407.13247)
    * Performs self-calibration on the target directions with facetselfcal (with automatically tuned parameter settings)

requirements:
  - class: SubworkflowFeatureRequirement
  - class: MultipleInputFeatureRequirement
  - class: InlineJavascriptRequirement

inputs:
    - id: msin
      type: Directory[]
      doc: The input MeasurementSets of the entire field-of-view with or without delay-calibration solutions applied.

    - id: source_catalogue
      type: File
      doc: External image catalogue (in CSV or FITS format) containing candidate target directions (e.g. LoTSS catalogue).

    - id: delay_solset
      type: File?
      doc: The solution tables generated by the delay calibration workflow in an HDF5 format when not applied on the msin.

    - id: dd_precorrections
      type: File?
      doc: Direction-dependent h5parm solutions to pre-apply before international LOFAR calibration.

    - id: freeze_dutch_solutions
      type: boolean
      default: false
      doc: If true, Dutch station solutions will be always be reset during the DD calibration. Useful if the pre-applied solution contain final Dutch station corrections.

    - id: validate
      type: boolean
      default: true
      doc: If set to true the pipeline will perform validation of the direction-dependent calibrator selection.

    - id: phasediff_score
      type: float
      default: 2.3
      doc: |
         Phasediff-score to select good calibrators and control the DD calibrator selection.
         See Section 3.3.1 from de Jong et al. (2024; https://arxiv.org/pdf/2407.13247)
         For calibrator selection <2.3 good for DD-calibrators and <0.7 good for DI-calibrators.
         If all sources should be selected, set this to a value >6.

    - id: custom_phasediff_score_csv
      type: File?
      doc: CSV-formatted file with phasediff_scores. Overwrites the scores one generated in the DD-selection.

    - id: peak_flux_cut
      type: float
      default: 0.025
      doc: Peak flux (Jy/beam) cut to pre-select sources from catalogue.

    - id: model_cache
      type: string?
      doc: Neural network cache directory.

    - id: max_rejected_fraction
      type: float?
      default: 0.3
      doc: |
         Maximum fraction of bad solutions. Lower value is stricter.
         Workflow crashes if fraction is exceeded.

    - id: chunk_size_directions
      type: int?
      default: 10
      doc: |
        Sets the number of directions to split off per DP3 explode call
        (enhances parallelisation and optimises the DP3 explode step)

steps:
    - id: split_directions
      label: Split out calibrator sources in separate measurement sets
      in:
        - id: msin
          source: msin
        - id: delay_solset
          source: delay_solset
        - id: image_cat
          source: source_catalogue
        - id: phasediff_score
          source: phasediff_score
        - id: peak_flux_cut
          source: peak_flux_cut
        - id: custom_phasediff_score_csv
          source: custom_phasediff_score_csv
        - id: dd_selection
          valueFrom: $(inputs.custom_phasediff_score_csv == null)
        - id: chunk_size_directions
          source: chunk_size_directions
      out:
        - msout_concat_strong
        - msout_concat_weak
        - msout_concat_unreliable
        - phasediff_score_csv
      run: ./split-directions.cwl

    # Strong calibrators
    - id: ddcal_int_strong
      label: Automatic direction-dependent calibration
      in:
        - id: msin
          source: split_directions/msout_concat_strong
        - id: dd_precorrections
          source: dd_precorrections
        - id: freeze_dutch_solutions
          source: freeze_dutch_solutions
        - id: phasediff_score_csv
          source:
            - custom_phasediff_score_csv
            - split_directions/phasediff_score_csv
          pickValue: first_non_null
        - id: model_cache
          source: model_cache
        - id: validate
          source: validate
        - id: max_rejected_fraction
          source: max_rejected_fraction
      out:
        - h5parms
        - selfcal_images
        - selfcal_inspection_images
        - solution_inspection_images
        - config_files
        - validation_csv
      run: ./subworkflows/ddcal_calibrators.cwl
      when: $(inputs.msin != null && inputs.msin.length > 0)

    - id: multidir_merge_strong
      in:
        - id: h5parms
          source: ddcal_int_strong/h5parms
      out:
        - multidir_h5
      run: ../steps/multidir_merger.cwl
      when: $(inputs.h5parms != null && inputs.h5parms.length > 0)

    - id: demote_strong_to_weak
      label: Identify strong sources which failed validation
      in:
        - id: msin
          source: split_directions/msout_concat_strong
        - id: validation_csv
          source: ddcal_int_strong/validation_csv
        - id: demote_from
          default: "strong"
        - id: demote_to
          default: "weak"
      out:
        - msout
      run: ../steps/demote_selection.cwl
      when: $(inputs.validation_csv != null)

    # Weak calibrators
    - id: ddcal_int_weak
      label: Automatic direction-dependent calibration
      in:
        - id: msin
          source:
            - split_directions/msout_concat_weak
            - demote_strong_to_weak/msout
          pickValue: all_non_null
          linkMerge: merge_flattened
        - id: dd_precorrections
          source: multidir_merge_strong/multidir_h5
        - id: freeze_dutch_solutions
          source: freeze_dutch_solutions
        - id: phasediff_score_csv
          source:
            - custom_phasediff_score_csv
            - split_directions/phasediff_score_csv
          pickValue: first_non_null
        - id: model_cache
          source: model_cache
        - id: validate
          source: validate
        - id: max_rejected_fraction
          source: max_rejected_fraction
      out:
        - h5parms
        - selfcal_images
        - selfcal_inspection_images
        - solution_inspection_images
        - config_files
        - validation_csv
      run: ./subworkflows/ddcal_calibrators.cwl
      when: $(inputs.msin != null && inputs.msin.length > 0)

    - id: multidir_merge_weak
      in:
        - id: h5parms
          source: ddcal_int_weak/h5parms
      out:
        - id: multidir_h5
      run: ../steps/multidir_merger.cwl
      when: $(inputs.h5parms != null && inputs.h5parms.length > 0)

    - id: demote_weak_to_unreliable
      label: Identify weak sources which failed validation
      in:
        - id: msin
          source: split_directions/msout_concat_weak
        - id: validation_csv
          source: ddcal_int_weak/validation_csv
        - id: demote_from
          default: "weak"
        - id: demote_to
          default: "unreliable"
      out:
        - msout
      run: ../steps/demote_selection.cwl
      when: $(inputs.validation_csv != null)

    # Unreliable calibrators
    - id: ddcal_int_unreliable
      label: Automatic direction-dependent calibration
      in:
        - id: msin
          source:
            - split_directions/msout_concat_unreliable
            - demote_weak_to_unreliable/msout
          pickValue: all_non_null
          linkMerge: merge_flattened
        - id: dd_precorrections
          source: multidir_merge_weak/multidir_h5
        - id: freeze_dutch_solutions
          source: freeze_dutch_solutions
        - id: phasediff_score_csv
          source:
            - custom_phasediff_score_csv
            - split_directions/phasediff_score_csv
          pickValue: first_non_null
        - id: model_cache
          source: model_cache
      out:
        - h5parms
        - selfcal_images
        - selfcal_inspection_images
        - solution_inspection_images
        - config_files
      run: ./subworkflows/ddcal_calibrators.cwl

    - id: store_configs
      label: Store selfcal config files
      in:
        - id: files
          source:
            - ddcal_int_strong/config_files
            - ddcal_int_weak/config_files
            - ddcal_int_unreliable/config_files
          linkMerge: merge_flattened
          pickValue: all_non_null
        - id: sub_directory_name
          default: selfcal_configs
      out:
        - id: dir
      run: ../steps/collectfiles.cwl

    - id: concat_validation_csvs
      label: Merge strong and weak validation
      in:
        - id: input_csvs
          source:
            - ddcal_int_strong/validation_csv
            - ddcal_int_weak/validation_csv
          pickValue: all_non_null
          linkMerge: merge_flattened
          valueFrom: $(self)
        - id: output_csv_name
          default: validation.csv
      out:
        - id: concat_csv
        - id: logfile
      run: ../steps/concat_csv.cwl
      when: $(inputs.input_csvs.length > 0)

outputs:
    - id: final_merged_h5
      type: File?
      outputSource: multidir_merge_weak/multidir_h5
      doc: Final multi-directional h5parm containing solutions in the directions of strong and weak 

    - id: phasediff_score_csv
      type: File?
      outputSource: split_directions/phasediff_score_csv
      doc: Phasediff-score CSV file

    - id: validation_csv
      type: File?
      outputSource: concat_validation_csvs/concat_csv
      doc: Validation CSV file

    - id: FITS_images
      type: File[]
      outputSource:
        - ddcal_int_strong/selfcal_images
        - ddcal_int_weak/selfcal_images
        - ddcal_int_unreliable/selfcal_images
      pickValue: all_non_null
      linkMerge: merge_flattened
      doc: Best self-calibration image in FITS format

    - id: calibration_solutions
      type: File[]?
      outputSource:
        - ddcal_int_strong/h5parms
        - ddcal_int_weak/h5parms
      pickValue: all_non_null
      linkMerge: merge_flattened
      doc: Best self-calibration solutions in h5parm format

    - id: solution_inspection_images
      type: Directory[]
      outputSource:
        - ddcal_int_strong/solution_inspection_images
        - ddcal_int_weak/solution_inspection_images
        - ddcal_int_unreliable/solution_inspection_images
      pickValue: all_non_null
      linkMerge: merge_flattened
      doc: LoSoTo solution inspection images

    - id: selfcal_PNG_images
      type: File[]
      outputSource:
        - ddcal_int_strong/selfcal_inspection_images
        - ddcal_int_weak/selfcal_inspection_images
        - ddcal_int_unreliable/selfcal_inspection_images
      pickValue: all_non_null
      linkMerge: merge_flattened
      doc: Self-calibration images in PNG format

    - id: selfcal_configs
      type: Directory
      outputSource: store_configs/dir
      doc: Configuration files used by facetselfcal.

    - id: msout
      type: Directory[]
      outputSource:
        - split_directions/msout_concat_strong
        - split_directions/msout_concat_weak
        - split_directions/msout_concat_unreliable
      pickValue: all_non_null
      linkMerge: merge_flattened
      doc: MeasurementSets of all (selected) directions
