class: Workflow
cwlVersion: v1.2
id: delay-calibration
label: VLBI delay calibration
doc: |
    The delay calibration pipeline does the following:
    * [If LINC target solutions are supplied]
      applies LINC solutions to target data and flags
      A-team sources,
    * [If LINC target solutions are supplied]
      concatenates the data in groups of 10, performs
      flagging on the international stations.
    * [If a DDF pipeline SOLSDIR directory is supplied]
      corrects direction-dependent effects for the Dutch stations and
      optionally subtracts the LoTSS model outside a user-specifiable region.
    * creates a MeasurementSet with data phase-shifted
      to a given delay calibrator, calibrated for direction-
      independent effects.

requirements:
  - class: SubworkflowFeatureRequirement
  - class: MultipleInputFeatureRequirement
  - class: StepInputExpressionRequirement
  - class: InlineJavascriptRequirement
  - class: ScatterFeatureRequirement

inputs:
    - id: msin
      type: Directory[]
      doc: The raw data in a MeasurementSet version 2.0 format.

    - id: solset
      type: File?
      doc: |
        The solution tables generated by the LINC target pipeline
        in an HDF5 format.

    - id: delay_calibrator
      type: File?
      doc: |
        A delay calibrator catalogue in CSV format.
        The input CSV should contain the following columns: Observation,Source_id,RA,DEC,Total_flux,Peak_flux
        If not provided, lofar-vlbi-plot will be run to generate the CSV (requires internet access).

    - id: image_catalogue
      type: File?
      doc: An image catalogue file in CSV format.

    - id: Ateam_skymodel
      doc: The skymodel to use in clipping bright sources.
      type: File

    - id: rfi_strategy
      doc: The RFI strategy to use in AOflagging.
      type: File

    - id: filter_baselines
      type: string?
      default: "*&"
      doc: The default filter constraints for the dp3_prep_target step.

    - id: flag_baselines
      type: string[]?
      default: []
      doc: |
        The baselines to be flagged by DP3.
        Can be a pattern, e.g. [ CS013HBA*&&* ].

    - id: phasesol
      type: string?
      default: TGSSphase
      doc: The name of the target solution table to use from the solset input.

    - id: reference_stationSB
      type: int?
      default: 104
      doc: |
        Subbands are concatenated in the concatenate-flag
        workflow relative to this station subband.

    - id: number_cores
      type: int?
      default: 12
      doc: |
        Number of cores to use per job for tasks with
        high I/O or memory.

    - id: max_dp3_threads
      type: int?
      default: 5
      doc: The number of threads per DP3 process.

    - id: ddf_solsdir
      type: Directory?
      doc: |
        [Required if subtracting LoTSS] Path to the SOLSDIR directory
        of the DDF-pipeline run, where most of the calibration solutions
        are stored.

    - id: ddf_rundir
      type: Directory?
      doc: |
        [Required if subtracting LoTSS] Path to the directory of the
        DDF-pipeline run where files required for the subtract can be found.

    - id: box_size
      type: float?
      default: 2.5
      doc: |
        [Required if subtracting LoTSS] Box size, in degrees, outside of which to subtract
        the LoTSS model from the data.

    - id: subtract_chunk_hours
      type: float?
      default: 0.5
      doc: |
        The range of time to predict the LoTSS model for at once. Lowering this value reduces
        memory footprint at the (possible) cost of increased runtime and vice versa.

    - id: do_subtraction
      type: boolean?
      default: false
      doc: When set to true, the LoTSS model will be subtracted from the DDF corrected data.

    - id: model_image
      type: File?
      doc: Image to generate an initial delay calibration model from.

    - id: apply_delay_solutions
      type: boolean?
      default: true
      doc: When set to true, the delay calibration solutions will be applied on the full MS.

    - id: do_validation
      type: boolean?
      default: true
      doc: Validate DI calibration, using merged output calibration solutions.

    - id: rm_correction
      type:
        type: enum
        symbols:
          - "RMextract"
          - "spinifex"
      default: "spinifex"
      doc: |
        The name of the target solution table to use from the solset input for
        rotation measure corrections.

    - id: select_best_n_delay_calibrators
      type: int?
      default: 1
      doc: Select this number of top-scoring delay calibrator candidates to attempt to calibrate.

    - id: starting_skymodel
      type:
        - File[]?
      doc: |
        Optional starting model(s) in FITS format used to kickstart the delay calibration when automatic selection from multiple delay candidates is used.
        If given and `do_auto_delay_selection` is enabled, the number of skymodels must be equal to `select_best_n_delay_calibrators`.
        Additionally, they should be named in such a way that when sorted by name, the delay calibrator MSes and skymodels end up in the same order.

    - id: do_auto_delay_selection
      type: boolean?
      default: false
      doc: |
        Automatically select the best delay calibrator based on phasediff scores.

steps:
    - id: setup
      label: setup
      in:
        - id: msin
          source: msin
        - id: solset
          source: solset
          valueFrom: $(self)
        - id: filter_baselines
          source: filter_baselines
        - id: flag_baselines
          source: flag_baselines
        - id: phasesol
          source: phasesol
        - id: number_cores
          source: number_cores
        - id: Ateam_skymodel
          source: Ateam_skymodel
        - id: rm_correction
          source: rm_correction
      out:
        - id: logdir
        - id: msout
        - id: summary_file
      run: ./setup.cwl
      when: $(inputs.solset != null)

    - id: lofar_vlbi_plot
      in:
        - id: msin
          source: msin
          valueFrom: $(self[0])
        - id: delay_calibrator
          source: delay_calibrator
      out:
        - id: delay_calibrator_pf
        - id: image_catalogue_pf
      run: ../steps/lofar_vlbi_plot.cwl
      when: $(inputs.delay_calibrator == null)

    - id: sort-concatenate-flag
      in:
        - id: msin
          source:
           - setup/msout
          pickValue: the_only_non_null
        - id: firstSB
          source: reference_stationSB
        - id: max_dp3_threads
          source: max_dp3_threads
        - id: rfi_strategy
          source: rfi_strategy
      out:
        - id: logdir
        - id: msout
        - id: summary_file
      run: ./concatenate-flag.cwl
      label: sort-concatenate-flag
      when: $(inputs.msin != null)

    - id: process_ddf
      in:
        - id: msin
          source:
            - sort-concatenate-flag/msout
            - msin
          pickValue: first_non_null
          valueFrom: $(self)
        - id: solsdir
          source: ddf_solsdir
          valueFrom: $(self)
        - id: ddf_rundir
          source: ddf_rundir
          valueFrom: $(self)
        - id: box_size
          source: box_size
        - id: ncpu
          source: number_cores
        - id: chunkhours
          source: subtract_chunk_hours
        - id: do_subtraction
          source: do_subtraction
      out:
        - id: msout
      run: ./process-ddf.cwl
      when: $(inputs.ddf_rundir != null && inputs.solsdir != null)

outputs:
  - id: msout
    outputSource: process_ddf/msout
    type: Directory[]
    doc: |
        The ddf-processed MeasurementSets.

