class: Workflow
cwlVersion: v1.2
id: split-directions
label: Split Directions
doc: |
  This is a workflow for the LOFAR-VLBI pipeline that
    * Splits a LOFAR MeasurementSet into various target directions
    * Applies delay calibrator solutions
    * Optionally (for wide-field imaging) performs direction-dependent calibrator selection
    * Optionally performs self-calibration on the target directions
  This step should be run after the delay calibration workflow.

requirements:
  - class: SubworkflowFeatureRequirement
  - class: MultipleInputFeatureRequirement
  - class: ScatterFeatureRequirement
  - class: InlineJavascriptRequirement

inputs:
    - id: msin
      type: Directory[]
      doc: Input MeasurementSets for individual frequency subbands covering the target directions.
    - id: delay_solset
      type: File?
      doc: The solution tables generated by the VLBI delay calibration workflow in an HDF5 format.
    - id: image_cat
      type: File
      doc: The image catalogue (in FITS or CSV format) containing the target directions.
      default: lotss_catalogue.csv
    - id: max_dp3_threads
      type: int?
      default: 4
      doc: Number of cores to use per job for
        tasks with high I/O or memory.
    - id: numbands
      type: int?
      default: -1
      doc: The number of bands to group. -1 means all bands.
    - id: truncateLastSBs
      type: boolean?
      default: true
      doc: Whether to truncate the last subbands of the
        MSs to the same length.
    - id: do_selfcal
      type: boolean?
      default: false
      doc: Whether to do selfcal on the direction concat MSs.
    - id: dd_selection
      type: boolean?
      default: false
      doc: If set to true the pipeline will perform direction-dependent calibrator selection.
    - id: phasediff_score
      type: float
      default: 2.3
      doc: |
         Phasediff-score for calibrator selection <2.3 good for DD-calibrators and <0.7 good for DI-calibrators.
         Only used when dd_selection==true.
    - id: select_best_n
      type: int?
      default: 0
      doc: Return only the best N sources. Only used when dd_selection=true.
    - id: peak_flux_cut
      type: float
      default: 0.0
      doc: Peak flux (Jy/beam) cut to pre-select sources from catalogue. Default at 0.0 is no peak flux selection.
    - id: configfile
      type: File?
      default: null
      doc: The configuration file to be used to run facetselfcal.py during the target_selfcal step.
    - id: frequency_resolution
      type: string?
      default: '390.56kHz'
      doc: |
        Frequency resolution for the split off datasets.
    - id: time_resolution
      type: string?
      default: '32.'
      doc: |
        Time resolution in seconds for the split off datasets.
    - id: chunk_size_directions
      type: int?
      default: 10
      doc: |
        Sets the number of directions to split off per DP3 explode call
        (enhances parallelisation and optimises the DP3 explode step)

steps:
    - id: select_bright_sources
      label: Select bright sources
      in:
        - id: msin
          source: msin
        - id: image_cat
          source: image_cat
        - id: peak_flux_cut
          source: peak_flux_cut
      out:
        - bright_cat
      when: $(inputs.peak_flux_cut > 0.0)
      run: ../steps/select_bright_sources.cwl

    - id: chunk_table
      label: Split source table into chunks
      in:
        - id: table
          source:
            - select_bright_sources/bright_cat
            - image_cat
          pickValue: first_non_null
        - id: chunk_size
          source: chunk_size_directions
      out:
        - csv_chunked
      run: ../steps/chunk_table.cwl

    - id: split_directions_sub_table
      label: Split direction with a catalogue and a given MeasurementSet
      in:
        - id: msin
          source: msin
        - id: image_cat
          source: chunk_table/csv_chunked
        - id: delay_solutions
          source: delay_solset
        - id: time_resolution
          source: time_resolution
        - id: frequency_resolution
          source: frequency_resolution
      out:
        - id: output_ms
      run: ./subworkflows/split_directions_sub_table.cwl
      scatter: [image_cat]
      scatterMethod: flat_crossproduct

    - id: flatten_msout
      label: Flatten msout
      in:
        - id: nestedarray
          source: split_directions_sub_table/output_ms
      out:
        - id: flattenedarray
      run: ../steps/flatten.cwl

    - id: phasediff_selection
      label: DD direction selection
      in:
        - id: msin
          source: flatten_msout/flattenedarray
        - id: dd_selection
          source: dd_selection
        - id: phasediff_score
          source: phasediff_score
        - id: select_best_n
          source: select_best_n
      out:
        - id: phasediff_score_csv
        - id: best_ms
      when: $(inputs.dd_selection)
      run: ./subworkflows/phasediff_selection.cwl

    - id: target_selfcal
      label: Target Selfcal
      in:
        - id: msin
          source:
            - phasediff_selection/best_ms
            - flatten_msout/flattenedarray
          pickValue: first_non_null
        - id: configfile
          source: configfile
        - id: do_selfcal
          source: do_selfcal
      out:
        - id: images
        - id: h5parm
      when: $(inputs.do_selfcal)
      run: ../steps/facet_selfcal.cwl
      scatter: msin

outputs:
    - id: msout_concat
      type: Directory[]
      outputSource:
        - phasediff_selection/best_ms
        - flatten_msout/flattenedarray
      pickValue: first_non_null
    - id: images
      type:
        type: array
        items:
          type: array
          items: File
      outputSource:
        - target_selfcal/images
      pickValue: the_only_non_null
    - id: phasediff_score_csv
      type: File?
      outputSource: phasediff_selection/phasediff_score_csv
    - id: h5parm
      type: 
        - File
        - File[]
      outputSource:
        - target_selfcal/h5parm
      pickValue: the_only_non_null
