class: Workflow
cwlVersion: v1.2
id: split-directions
label: Split Directions
doc: |
  This is a workflow for the LOFAR-VLBI pipeline that
    * Splits a LOFAR MeasurementSet into various target directions
    * Applies delay calibrator solutions
    * Optionally (for wide-field imaging) performs direction-dependent calibrator selection
  This workflow should be run on data processed by the delay calibration workflow if run manually, but is typically run automatically by dd-calibration.

requirements:
  - class: SubworkflowFeatureRequirement
  - class: MultipleInputFeatureRequirement
  - class: ScatterFeatureRequirement
  - class: InlineJavascriptRequirement

inputs:
    - id: msin
      type: Directory[]
      doc: Input MeasurementSets for individual frequency subbands covering the target directions.
    - id: delay_solset
      type: File?
      doc: The solution tables generated by the VLBI delay calibration workflow in an HDF5 format.
    - id: image_cat
      type: File
      doc: The image catalogue (in FITS or CSV format) containing the target directions.
      default: lotss_catalogue.csv
    - id: dd_selection
      type: boolean?
      default: false
      doc: If set to true the pipeline will generate phasediff scores for direction-dependent calibrator selection.
    - id: phasediff_score
      type: float
      default: 2.3
      doc: |
         Phasediff-score for calibrator selection <2.3 good for DD-calibrators and <0.7 good for DI-calibrators.
         Only used when dd_selection==true.
    - id: select_best_n
      type: int?
      default: 0
      doc: Return only the best N sources. Only used when dd_selection=true.
    - id: peak_flux_cut
      type: float
      default: 0.0
      doc: Peak flux (Jy/beam) cut to pre-select sources from catalogue. Default at 0.0 is no peak flux selection.
    - id: frequency_resolution
      type: string?
      default: '390.56kHz'
      doc: |
        Frequency resolution for the split off datasets.
    - id: time_resolution
      type: string?
      default: '32.'
      doc: |
        Time resolution in seconds for the split off datasets.
    - id: chunk_size_directions
      type: int?
      default: 10
      doc: |
        Sets the number of directions to split off per DP3 explode call
        (enhances parallelisation and optimises the DP3 explode step)

steps:
    - id: select_bright_sources
      label: Select bright sources
      in:
        - id: msin
          source: msin
        - id: image_cat
          source: image_cat
        - id: peak_flux_cut
          source: peak_flux_cut
      out:
        - bright_cat
      when: $(inputs.peak_flux_cut > 0.0)
      run: ../steps/select_bright_sources.cwl

    - id: chunk_table
      label: Split source table into chunks
      in:
        - id: table
          source:
            - select_bright_sources/bright_cat
            - image_cat
          pickValue: first_non_null
        - id: chunk_size
          source: chunk_size_directions
      out:
        - csv_chunked
      run: ../steps/chunk_table.cwl

    - id: split_directions_sub_table
      label: Split direction with a catalogue and a given MeasurementSet
      in:
        - id: msin
          source: msin
        - id: image_cat
          source: chunk_table/csv_chunked
        - id: delay_solutions
          source: delay_solset
        - id: time_resolution
          source: time_resolution
        - id: frequency_resolution
          source: frequency_resolution
      out:
        - id: output_ms
      run: ./subworkflows/split_directions_sub_table.cwl
      scatter: [image_cat]
      scatterMethod: flat_crossproduct

    - id: flatten_msout
      label: Flatten msout
      in:
        - id: nestedarray
          source: split_directions_sub_table/output_ms
      out:
        - id: flattenedarray
      run: ../steps/flatten.cwl

    - id: phasediff_selection
      label: DD direction selection
      in:
        - id: msin
          source: flatten_msout/flattenedarray
        - id: dd_selection
          source: dd_selection
        - id: phasediff_score
          source: phasediff_score
        - id: select_best_n
          source: select_best_n
      out:
        - id: phasediff_score_csv
        - id: strong_ms
        - id: weak_ms
        - id: unreliable_ms
      when: $(inputs.dd_selection)
      run: ./subworkflows/phasediff_selection.cwl

outputs:
    - id: msout_concat_strong
      type: Directory[]
      outputSource:
        - phasediff_selection/strong_ms
      pickValue: all_non_null
      linkMerge: merge_flattened
    - id: msout_concat_weak
      type: Directory[]
      outputSource:
        - phasediff_selection/weak_ms
      pickValue: all_non_null
      linkMerge: merge_flattened
    - id: msout_concat_unreliable
      type: Directory[]
      outputSource:
        - phasediff_selection/unreliable_ms
      pickValue: all_non_null
      linkMerge: merge_flattened
    - id: phasediff_score_csv
      type: File?
      outputSource: phasediff_selection/phasediff_score_csv
