cwlVersion: v1.2
class: CommandLineTool
id: facet_selfcal
label: Facet Selfcal
doc: |
    Performs direction independent calibration
    of the international antenna array.

baseCommand: facetselfcal

arguments:
  - prefix: --auto
    valueFrom: $(inputs.configfile == null) 
inputs:
    - id: msin
      type: Directory
      inputBinding:
        position: 1
      doc: |
        Input data phase-shifted to the
        delay calibrator in MeasurementSet format.

    - id: skymodel
      type: File?
      inputBinding:
        position: 0
        prefix: --skymodel
        separate: true
      doc: |
        The skymodel to be used in the first
        cycle in the self-calibration.

    - id: configfile
      type: File?
      inputBinding:
        position: 0
        prefix: --configpath
        separate: true
      doc: A plain-text file containing configuration options for self-calibration.

    - id: number_cores
      type: int?
      default: 12
      doc: The number of cores that should be allocated for the self-calibration.

outputs:
    - id: h5parm
      type: File
      outputBinding:
        glob: [merged_selfcalcycle*.h5, merged_addCS_selfcalcycle*.h5]
        outputEval: $(self[self.length - 1])
      doc: |
        The calibration solution files generated
        by lofar_facet_selfcal in HDF5 format.

    - id: images
      type: File[]
      outputBinding:
        glob: ['*.png', plotlosoto*/*.png, '*MFS-image.fits']
      doc: |
        Delay calibrator images generated by lofar_facet_selfcal in PNG and FITS format, and solution plots from LoSoTo.

    - id: fits_images
      type: File[]
      outputBinding:
        glob: '*MFS-image.fits'

    - id: logfile
      type: File[]
      outputBinding:
         glob: [facet_selfcal*.log, selfcal.log]
      doc: |
        The files containing the stdout
        and stderr from the step.

requirements:
  - class: ShellCommandRequirement
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - entry: $(inputs.msin)
  - class: ResourceRequirement
    coresMin: $(inputs.number_cores)
    ramMin: 60000

hints:
  - class: DockerRequirement
    dockerPull: vlbi-cwl

stdout: facet_selfcal.log
stderr: facet_selfcal_err.log
